language: python
sudo: required
dist: bionic
matrix:
    include:
      - python: 2.7
      - python: 3.5
before_install:
   - sudo apt-get update -y
   - sudo apt-get install -y --no-install-recommends --fix-missing ca-certificates g++ libsndfile1 llvm-7 make wget
install:
   - source ci/install.sh
script:
   - bash ci/test.sh
notifications:
  email: false
